stages:
  - 'Install Project'
  - 'Code Quality: Run'

default:
  image: registry.e-sites.nl/ops/e-containers/php:7.4-alpine

install:backend:
  stage: 'Install Project'
  environment:
    name: $CI_COMMIT_REF_NAME
  tags:
    - aws
  artifacts:
    paths:
      - vendor/
    expire_in: 1 hour
  script:
    - COMPOSER_MEMORY_LIMIT=4G composer update

phpinsights:
  stage: 'Code Quality: Run'
  tags:
    - aws
  except:
    - master
  dependencies:
    - install:backend
  script:
    - composer phpinsights | tee phpinsights_results.txt
  artifacts:
    when: always
    expire_in: 1 hour
    paths:
      - phpinsights_results.txt

phpstan:
  stage: 'Code Quality: Run'
  tags:
    - aws
  except:
    - master
  dependencies:
    - install:backend
  script:
    - composer phpstan | tee phpstan_results.xml
  artifacts:
    when: always
    expire_in: 1 hour
    paths:
      - phpstan_results.xml

phpmd:
  stage: 'Code Quality: Run'
  tags:
    - aws
  except:
    - master
  dependencies:
    - install:backend
  script:
    - composer phpmd | tee phpmd_results.xml
  artifacts:
    when: always
    expire_in: 1 hour
    paths:
      - phpmd_results.xml

phpcpd:
  stage: 'Code Quality: Run'
  tags:
    - aws
  except:
    - master
  dependencies:
    - install:backend
  script:
    - composer phpcpd | tee phpcpd_results.xml
  artifacts:
    when: always
    expire_in: 1 hour
    paths:
      - phpcpd_results.xml

phpcs:
  stage: 'Code Quality: Run'
  tags:
    - aws
  except:
    - master
  dependencies:
    - install:backend
  script:
    - composer phpcs | tee phpcs_results.xml
  artifacts:
    when: always
    expire_in: 1 hour
    paths:
      - phpcs_results.xml
