services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Esites\KunstmaanExtrasBundle\DataFixtures\ORM\:
    resource: '../../DataFixtures/ORM'
    tags:
      - { name: doctrine.fixture.orm }

  Esites\KunstmaanExtrasBundle\Helper\:
    resource: '../../Helper'

  Esites\KunstmaanExtrasBundle\Logger\:
    resource: '../../Logger'

  Esites\KunstmaanExtrasBundle\Service\:
    resource: '../../Service'

  Esites\KunstmaanExtrasBundle\Twig\:
    resource: '../../Twig'

  Esites\KunstmaanExtrasBundle\Helper\PageCreator:
    arguments:
      $pageCreatorService: '@kunstmaan_node.page_creator_service'
      $requiredLocales: "%requiredlocales%"

  Esites\KunstmaanExtrasBundle\Service\MailerService:
    arguments:
      $fromEmail: "%esites_kunstmaan_extras.mailer_user%"
      $fromName: "%esites_kunstmaan_extras.mailer_name%"